/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
/**
 *
 * @author nicolagabrielecolarusso
 */
public class AppleHp extends javax.swing.JFrame {
    /**
     * Creates new form Apple
     */
    
    public static HpSimulador home;
            
    public AppleHp() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inicioLabel = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        HpBoton = new javax.swing.JButton();
        AppleBoton = new javax.swing.JButton();
        ConfiguracionBoton = new javax.swing.JButton();
        DashboardBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();
        fotoApple = new javax.swing.JLabel();
        fotoHp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(937, 688));
        setMinimumSize(new java.awt.Dimension(937, 688));
        setPreferredSize(new java.awt.Dimension(937, 688));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setForeground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 550, 570));

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        inicioLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        inicioLabel.setText("Inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(inicioLabel)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(inicioLabel)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 160, 50));

        titulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("TechNexus");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        HpBoton.setBackground(new java.awt.Color(102, 102, 102));
        HpBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        HpBoton.setForeground(new java.awt.Color(255, 255, 255));
        HpBoton.setText("HP");
        HpBoton.setBorder(null);
        HpBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpBotonActionPerformed(evt);
            }
        });
        jPanel1.add(HpBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 50));

        AppleBoton.setBackground(new java.awt.Color(102, 102, 102));
        AppleBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AppleBoton.setForeground(new java.awt.Color(255, 255, 255));
        AppleBoton.setText("Apple");
        AppleBoton.setBorder(null);
        AppleBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleBotonActionPerformed(evt);
            }
        });
        jPanel1.add(AppleBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 50));

        ConfiguracionBoton.setBackground(new java.awt.Color(102, 102, 102));
        ConfiguracionBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ConfiguracionBoton.setForeground(new java.awt.Color(255, 255, 255));
        ConfiguracionBoton.setText("Configuración");
        ConfiguracionBoton.setBorder(null);
        ConfiguracionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionBotonActionPerformed(evt);
            }
        });
        jPanel1.add(ConfiguracionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 160, 50));

        DashboardBoton.setBackground(new java.awt.Color(102, 102, 102));
        DashboardBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        DashboardBoton.setForeground(new java.awt.Color(255, 255, 255));
        DashboardBoton.setText("Dashboard");
        DashboardBoton.setBorder(null);
        DashboardBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardBotonActionPerformed(evt);
            }
        });
        jPanel1.add(DashboardBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 160, 50));

        GuardarBoton.setBackground(new java.awt.Color(102, 102, 102));
        GuardarBoton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        GuardarBoton.setForeground(new java.awt.Color(255, 255, 255));
        GuardarBoton.setText("Guardar");
        GuardarBoton.setBorder(null);
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 160, 50));

        fotoApple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fotoCompApple.png"))); // NOI18N
        fotoApple.setText("jLabel1");
        jPanel1.add(fotoApple, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        fotoHp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fotoCompHp.png"))); // NOI18N
        fotoHp.setText("jLabel1");
        jPanel1.add(fotoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HpBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpBotonActionPerformed
        HpSimulador home = new HpSimulador(this);
    }//GEN-LAST:event_HpBotonActionPerformed

    private void AppleBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleBotonActionPerformed

    private void ConfiguracionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfiguracionBotonActionPerformed

    private void DashboardBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardBotonActionPerformed

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppleHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppleHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppleHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppleHp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppleHp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppleBoton;
    private javax.swing.JButton ConfiguracionBoton;
    private javax.swing.JButton DashboardBoton;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JButton HpBoton;
    private javax.swing.JLabel fotoApple;
    private javax.swing.JLabel fotoHp;
    private javax.swing.JLabel inicioLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
